import stats from "@/data/eda-stats.json";
import type { DatasetStats, LabelShare, LengthBin, WordFrequency } from "@/types";

/**
 * The stats file is generated by `scripts/compute_eda.py` and copied into the web app
 * on purpose: the dataset view then works while the API is asleep, spends none of the
 * public rate-limit budget, and needs no endpoint. `tests/test_eda_sync.py` fails if
 * the copy drifts from `models/eda/stats.json`.
 */
type RawStats = {
  label_counts: Record<string, number>;
  length_histogram: { bin_edges: number[]; counts: number[] };
  top_words_by_label: Record<string, (string | number)[][]>;
  word_tokenizer: string;
};

/** JSON widens [word, frequency] to (string | number)[]; narrow it instead of casting blindly. */
function wordRows(rows: (string | number)[][]): [string, number][] {
  const pairs: [string, number][] = [];
  for (const row of rows) {
    const [word, frequency] = row;
    if (typeof word === "string" && typeof frequency === "number") pairs.push([word, frequency]);
  }
  return pairs;
}

const raw = stats as RawStats;

export const datasetStats: DatasetStats = {
  ...raw,
  top_words_by_label: Object.fromEntries(
    Object.entries(raw.top_words_by_label).map(([label, rows]) => [label, wordRows(rows)]),
  ),
};

export const POSITIVE = "긍정";
export const NEGATIVE = "부정";

export function totalReviews(source: DatasetStats = datasetStats): number {
  return Object.values(source.label_counts).reduce((sum, count) => sum + count, 0);
}

export function labelShares(source: DatasetStats = datasetStats): LabelShare[] {
  const total = totalReviews(source);
  return [POSITIVE, NEGATIVE].map((label) => {
    const count = source.label_counts[label] ?? 0;
    return { label, count, share: total > 0 ? count / total : 0 };
  });
}

/** Bin centres weighted by their counts: the file keeps the histogram, not the raw lengths. */
export function meanLength(source: DatasetStats = datasetStats): number {
  const { bin_edges: edges, counts } = source.length_histogram;
  const total = counts.reduce((sum, count) => sum + count, 0);
  if (total === 0) return 0;
  const weighted = counts.reduce((sum, count, index) => {
    const centre = (edges[index] + edges[index + 1]) / 2;
    return sum + centre * count;
  }, 0);
  return weighted / total;
}

export function lengthBins(source: DatasetStats = datasetStats): LengthBin[] {
  const { bin_edges: edges, counts } = source.length_histogram;
  const peak = Math.max(...counts, 0);
  return counts.map((count, index) => ({
    label: `${Math.round(edges[index])}~${Math.round(edges[index + 1])}`,
    count,
    share: peak > 0 ? count / peak : 0,
  }));
}

/** Descending frequency so the chart reads top-down like the Streamlit tab. */
export function topWords(label: string, source: DatasetStats = datasetStats): WordFrequency[] {
  const rows = source.top_words_by_label[label] ?? [];
  const peak = Math.max(...rows.map(([, frequency]) => frequency), 0);
  return rows
    .map(([word, frequency]) => ({ word, frequency, share: peak > 0 ? frequency / peak : 0 }))
    .sort((left, right) => right.frequency - left.frequency);
}

export function tokenizerLabel(source: DatasetStats = datasetStats): string {
  return source.word_tokenizer === "okt" ? "Okt 형태소 분석" : "간이 토크나이저(공백 분리)";
}
